"""add_investor_relations_url_to_companies

Revision ID: b2ef5543a91e
Revises: 2b55687d000a
Create Date: 2026-05-07 18:18:05.807249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2ef5543a91e'
down_revision: Union[str, None] = '2b55687d000a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('investor_relations_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'investor_relations_url')
    # ### end Alembic commands ###
